In [1]:
#IMPORTANDO BIBLIOTECAS
import numpy as np
import os
import pandas as pd
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn import metrics
from sklearn.model_selection import train_test_split 
import pymysql
import urllib3
import urllib
from sqlalchemy import create_engine
import pyodbc 

C:\Users\robson.miranda\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [2]:
#Criando a conexão com o banco de dados SQL Server
params = urllib.parse.quote_plus("DRIVER={ODBC Driver 17 for SQL Server};SERVER=MTZDSKFS008465\SQLEXPRESS01;DATABASE=BRASILEIRO;UID=sa;PWD=123")
engine = create_engine("mssql+pyodbc:///?odbc_connect=%s" % params)

print("Connection established") 

Connection established


In [ ]:
#Criando a conexão com o banco de dados MySQL
#engine = create_engine("mysql+pymysql://posbi15_app:x8xVYFfwBYZBFud@35.239.231.2/db_mining")

In [3]:
#Criando o método para o Naive Bayes
def naiveBayes(train_X, train_Y, test_X):
    X = train_X[:]
    Y = train_Y[:]
    X_test = test_X[:]
    model_NB = MultinomialNB(alpha=0.0)
    model_NB.fit(X, Y)
    predictedNB = model_NB.predict(X_test)
    return predictedNB

In [4]:
#Criando o método para o SVM
def svmachine(train_X, train_Y, test_X):
    X = train_X[:]
    Y = train_Y[:]
    X_test = test_X[:]
    clf = svm.SVC()
    clf.fit(X, Y)
    predictedSVM = clf.predict(X_test)
    return predictedSVM

In [5]:
#Criando o método para o Random Forest
def randomForest(train_X, train_Y, test_X):
    X = train_X[:]
    Y = train_Y[:]
    X_test = test_X[:]
    forest = RandomForestClassifier(10)
    forest.fit(X, Y)
    predictedRF = forest.predict(X_test)
    return predictedRF

In [6]:
# Criando o método para o Resultado 
def methodResults(predictedY, correctY):
    rightCount = 0
    for i in range (0, len(correctY), 1):
        if predictedY[i] == correctY[i]:
            rightCount = rightCount + 1

    percent = (float(rightCount) / len(test_batch_Y)) * 100
    print ("  Percent: ", percent)

In [7]:
# Criando o método para matriz de confusão
def methodConfusionMatrix(predictedY, correctY):
    from sklearn.metrics import classification_report, confusion_matrix  
    print(confusion_matrix(correctY,predictedY))  
    print(classification_report(correctY,predictedY)) 
    

In [8]:
if __name__ == '__main__':
    
    test_batch_Y = []
    
    #bankdata = pd.read_excel(r'C:\Users\Cristiano\Desktop\TCC - POS GRADUACAO\BASES\Modelagem_Base_Machine_Learning_2002.xlsx')
    bankdata = pd.read_sql("SELECT * FROM DECIMA_RODADA_FRENTE", engine)
 
    bankdata.head()     

    X = bankdata.drop('TC_RESULTADO', axis=1)  
    y = bankdata['TC_RESULTADO']

    X_train_np, X_test_np, Y_train_np, Y_test_np = train_test_split(X, y, test_size = 0.20) 
    
    #creating np data
    X_train_np = np.array(X_train_np)
    Y_train_np = np.array(Y_train_np)
    X_test_np = np.array(X_test_np)
    Y_test_np = np.array(Y_test_np)

    print ("--------------------------------------")
    print ("Predicting outcome of football matches")
    print ("--------------------------------------")
    print ("Number of games from datasets: ", len(X_train_np))
    print ("Number of test games:          ", len(X_test_np))
    print ("")
    
    test_batch_Y = Y_test_np
    
    predNB = naiveBayes(X_train_np, Y_train_np, X_test_np)
    print ("Results of Naive Bayes:")
    methodResults(predNB, Y_test_np)
    methodConfusionMatrix(predNB, Y_test_np)
    
    #print(Y_test_np[1])
    
    predRF = randomForest(X_train_np, Y_train_np, X_test_np)
    print ("Results of Random Forest:")
    methodResults(predRF, Y_test_np)
    methodConfusionMatrix(predRF, Y_test_np)
    #print(metrics.classification_report(Y_test_np, predNB))

    predSVM = svmachine(X_train_np, Y_train_np, X_test_np)
    print ("Results of Support Vectors Machine:")
    methodResults(predSVM, Y_test_np)
    methodConfusionMatrix(predSVM, Y_test_np)

--------------------------------------
Predicting outcome of football matches
--------------------------------------
Number of games from datasets:  928
Number of test games:           232

Results of Naive Bayes:
  Percent:  47.41379310344828
[[22 44  1]
 [24 87  2]
 [12 39  1]]
             precision    recall  f1-score   support

        0.0       0.38      0.33      0.35        67
        1.0       0.51      0.77      0.61       113
        2.0       0.25      0.02      0.04        52

avg / total       0.41      0.47      0.41       232

2.0
Results of Random Forest:
  Percent:  44.827586206896555
[[14 43 10]
 [18 85 10]
 [15 32  5]]
             precision    recall  f1-score   support

        0.0       0.30      0.21      0.25        67
        1.0       0.53      0.75      0.62       113
        2.0       0.20      0.10      0.13        52

avg / total       0.39      0.45      0.40       232

Results of Support Vectors Machine:
  Percent:  48.706896551724135
[[  0  67   0]
 [ 

C:\Users\robson.miranda\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\naive_bayes.py:472: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10
  'setting alpha = %.1e' % _ALPHA_MIN)
C:\Users\robson.miranda\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
